### ISSUE TITLE
Page programme: description 

### ISSUE THREAD

**Issue by Fanevanjanahary** [OpenStreetMap-Madagascar/sotm-madagascar#10]
@vinber des propostion pour modifier cette description? 

![image](https://github.com/OpenStreetMap-Madagascar/sotm-madagascar/assets/12623986/db7f40a7-30c0-4950-90cd-7db917228193)

**Comment by vinber** [comment]
29 et 30 sont lundi et mardi.

Et pour l'instant nous pouvons préciser que le programme est en cours d'élaboration, avec un appel à conférence, atelier, ...

**Comment by Fanevanjanahary** [comment]
@MaminiainaIndrafo 
![image](https://github.com/OpenStreetMap-Madagascar/sotm-madagascar/assets/12623986/8b934e0e-3db3-4b5b-94da-02f0ced978f6)

**Comment by MaminiainaIndrafo** [comment]
C'est corrigé
