### ISSUE TITLE
"page" à propos

### ISSUE THREAD

**Issue by vinber** [OpenStreetMap-Madagascar/sotm-madagascar#12]
Quelques propositions de corrections

- À propos de SoTM -> À propos de So**t**M Madagasikara

Pour le texte, proposition, avec une reprise partielle du texte du sotm-fr (je fais avec ce que je connais)

State of the Map Madagasikara est la première rencontre nationale OpenstreetMap . Cet évènement vise à regrouper pendant 2 jours, les 29 et 30 avril les contributrices et contributeurs, utilisateurs, représentants de collectivités, d'entreprises, chercheurs mais aussi toute personne curieuse de découvrir cette « carte libre du monde » que représente OpenStreetMap.
Les State of the Map sont des occasions de se tenir informé, se former, découvrir l'écosystème et les multiples applications -existantes ou à imaginer- autour d'OpenStreetMap.
Nous vous y attendons nombreuses et nombreux.

**Comment by MaminiainaIndrafo** [comment]
Je pense qu'il faut remplacer tous les occurrences de "Madagascar" sur le site par "Madagasikara", n'est-ce pas ?
