### ISSUE TITLE
Appel à proposition

### ISSUE THREAD

**Issue by vinber** [OpenStreetMap-Madagascar/sotm-madagascar#14]
Je pense qu'il faudrait un bouton Appel à propositions sur la page d'accueil, qui pointe sur 

https://framaforms.org/proposition-dintervention-au-sotm-madagascar-2024-1707755223

Actuellement le bouton "s'inscrire" pointe sur l'ancienne url de l'appel à proposition, ceux sont 2 choses différentes.

où alors dans le menu vertical, une page ou l'on peut inclure l'appel à propositions ?

mais peut-être pour commencer un bouton appel à proposition pointant vers https://framaforms.org/proposition-dintervention-au-sotm-madagascar-2024-1707755223

**Comment by MaminiainaIndrafo** [comment]
On va d'abord changer le libellé du bouton "S'inscrire" par "Appel à proposition", qui redirige vers https://framaforms.org/proposition-dintervention-au-sotm-madagascar-2024-1707755223. Ensuite, nous placerons le bouton "S'inscrire" dans le menu vertical et dans le pied de page. Qu'en pensez-vous ?

**Comment by vinber** [comment]
que si tu me vouvoies, je te mords lorsque l'on se voit :)

et je pense que c'est la meilleure façon de faire effectivement

**Comment by vinber** [comment]
> que si tu me vouvoies, je te mords lorsque l'on se voit :)

mais tu t'adressais à tout le monde en fait !
