### ISSUE TITLE
Site SotM

### ISSUE THREAD

**Issue by Xavamlo** [OpenStreetMap-Madagascar/sotm-madagascar#17]
La page est beaucoup mieux avec la carte OSM de Fianar en fond.
Je pense en revanche que ce gros logo OSM sur fond blanc au milieu de la page n'est pas adapté. Ce n'est pas l'information centrale. 
Encore une fois, je propose de mettre ce logo en vis à vis du logo SotM, à la place du bouton "contact".
Les boutons "contact", "appel à proposition", "s'inscrire" devraient être ensemble et ne correspondent pas au même type d'information que "accueil", "a propos", "programme", "sponsor", "en savoir plus" qui décrivent le plan de la page alors que les boutons renvoient à des formulaires.

**Comment by Xavamlo** [comment]
Pour les partenaires, il manque le logo de l'IRD

**Comment by Xavamlo** [comment]
C'est beaucoup mieux. Le visuel est vraiment bien, je trouve. Et le texte est beaucoup plus clair.
Ça reste un peut confus entre les boutons et les éléments du sommaire en haut de la page.
Le sommaire "à propos" pointe sur la même chose que le bouton "en savoir plus".
Je propose de distinguer, en haut, uniquement les éléments de sommaire qui permettent de se déplacer à différents endroit de la page ; et plus bas, des boutons qui renvoient à des formulaires : "s'inscrire", "contribuer" (au lieu de "appel à proposition"), "nous contacter".  Ces 3 boutons peuvent être mis en bas de la 1ere page. 
Il faudrait également distinguer les "sponsors" des "organisateurs". Les organisateurs et leurs logos pourraient être mis dans la rubrique "a propos de SotM Madagasikara", après le paragraphe de présentation, on pourrait rajouter  : "Cette manifestation est co-organisée par l'association OpenStreetMap Madagascar et le projet Madatlas (Université de Fianarantsoa, Université Gustave Eiffel, Université Bordeaux Montaigne, IRD) avec en gros les logos OSM Mada, UF et Madatlas et, en plus petit, en dessous de celui de Madatlas et de l'UF,  ceux de l'IRD (moins grand que l'actuel), de l'Univ G. Eiffel et de UBM.

**Comment by MaminiainaIndrafo** [comment]
J'ai déjà réorganisé les menus, mais concernant le bouton "Nous contacter", je pense qu'il est préférable qu'il reste à gauche. De plus, sa couleur n'est pas la même que celle des autres éléments du menu, ce qui le distingue des autres.

Les logos des organisateurs sont déjà dans la même section que "À propos de SotM Madagasikara", et je les trouve également bien ainsi.
