### ISSUE TITLE
DNS OK https://sotm2024.openstreetmap.mg/

### ISSUE THREAD

**Issue by vinber** [OpenStreetMap-Madagascar/sotm-madagascar#19]
à priori les dns sont ok

 I have now made the DNS chanegs:
https://github.com/openstreetmap/dns/commit/e80b3455187e180528359ecfc31a04f39d468738
 
If you need any further changes please Pull Request the changes here:
https://github.com/openstreetmap/dns/blob/master/src/openstreetmap-mg.js 

sans doute qu'il y a quelques choses à faire coté github !

**Comment by vinber** [comment]
Problème de certificat également https://sotm2024.openstreetmap.mg/

**Comment by MaminiainaIndrafo** [comment]
La partie Github est configurée, le site est désormais disponible sur https://sotm2024.openstreetmap.mg/ 👌
