### ISSUE TITLE
mise à jour du programme

### ISSUE THREAD

**Issue by vinber** [OpenStreetMap-Madagascar/sotm-madagascar#23]
j'ai tenté quelques corrections pour la page programme mais je ne suis pas sur de moi dans le processus de pull request https://github.com/OpenStreetMap-Madagascar/sotm-madagascar/pull/22

**Comment by MaminiainaIndrafo** [comment]
Est ce que c'est bon maintenant ? Il faut l'approbation des mainteneurs pour ton Pull Request

**Comment by MaminiainaIndrafo** [comment]
la partie session auto-organisée c'est juste un copié collé du site sotm 2019 de ce qui existait avant

**Comment by vinber** [comment]
oui en fait peut-être peut-on le retirer complétement ?

**Comment by MaminiainaIndrafo** [comment]
D'accord, ça marche 👌
