### ISSUE TITLE
url pour voir le site

### ISSUE THREAD

**Issue by vinber** [OpenStreetMap-Madagascar/sotm-madagascar#4]
je me suis mal exprimé dans la précédente issue.

dans le readme, je m'attendais à trouver l'ur pour voir le site actuellement :)

c'est possible ?

**Comment by MaminiainaIndrafo** [comment]
On est encore en train de configurer avec le nom de domaine, mais une fois que c'est fait, je vous l'envoie et je le mettrai également dans le README.

**Comment by MaminiainaIndrafo** [comment]
J'ai quand même ajouté l'URL actuelle sur https://openstreetmap-madagascar.github.io/sotm-madagascar/ dans le README.

**Comment by vinber** [comment]
> J'ai quand même ajouté l'URL actuelle sur https://openstreetmap-madagascar.github.io/sotm-madagascar/ dans le README.

parfait c'est celle que je souhaitais, que je n'arrivais ni à trouver ni donc à partager :) merci beaucoup
